type t = int

(* type t = *)
(*   { display_name : string *)
(*   ; first_name : string option *)
(*   ; last_name : string option *)
(*   } *)

(* let make ?first_name ?last_name display_name = *)
(*   { display_name; first_name; last_name } *)
(* ;; *)

(* let as_name = *)
(*   let open Yocaml.Data.Validation in *)
(*   string $ String.trim & String.not_blank & String.length_ge 1 *)
(* ;; *)

(* let from_triple = function *)
(*   | Some a, Some b, Some c -> Ok (a, Some b, Some c) *)
(*   | None, Some b, Some c -> *)
(*     let a = b ^ " " ^ c in *)
(*     Ok (a, Some b, Some c) *)
(*   | _ -> *)
(*     let error = *)
(*       Yocaml.Data.Validation.Missing_field { field = "display_name" } *)
(*       |> Yocaml.Nel.singleton *)
(*     in *)
(*     Error error *)
(* ;; *)

(* let validate_name fields = *)
(*   let open Yocaml.Data.Validation in *)
(*   let+ display_name = *)
(*     opt *)
(*       fields *)
(*       "display_name" *)
(*       ~alt: *)
(*         [ "nick" *)
(*         ; "nickname" *)
(*         ; "user" *)
(*         ; "username" *)
(*         ; "displayname" *)
(*         ; "name" *)
(*         ; "designation" *)
(*         ; "denotation" *)
(*         ; "alias" *)
(*         ; "aka" *)
(*         ; "cognomen" *)
(*         ; "handle" *)
(*         ; "dname" *)
(*         ] *)
(*       as_name *)
(*   and+ first_name = *)
(*     opt *)
(*       fields *)
(*       "first_name" *)
(*       ~alt: *)
(*         [ "given_name"; "firstname"; "forename"; "fname"; "givenname"; "gname" ] *)
(*       as_name *)
(*   and+ last_name = *)
(*     opt fields "last_name" ~alt:[ "lastname"; "lname" ] as_name *)
(*   in *)
(*   display_name, first_name, last_name *)
(* ;; *)

(* let from_record = *)
(*   let open Yocaml.Data.Validation in *)
(*   record (fun fields -> *)
(*     let+ display_name, first_name, last_name = *)
(*       (validate_name & from_triple) fields *)
(*     in *)
(*     make ?first_name ?last_name display_name) *)
(* ;; *)
